CREATE TABLE IF NOT EXISTS products (
  id TEXT NOT NULL,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  isActive BOOLEAN NOT NULL,
  description TEXT,
  minValue DOUBLE PRECISION NOT NULL,
  taxPercentage INTEGER NOT NULL,
  type TEXT NOT NULL,
  category_id TEXT NOT NULL,
  price_1 DOUBLE PRECISION NOT NULL,
  price_2 DOUBLE PRECISION NOT NULL,
  price_3 DOUBLE PRECISION NOT NULL,
  price_4 DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_products PRIMARY KEY (id)
);
