ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS last_modified_date TIMESTAMP;
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(50);
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS last_modified_by VARCHAR(50);